### ISSUE TITLE
Skynet does honor banning 1.1.1.1, 1.0.0.1, 8.8.8.8 or 8.8.4.4

### ISSUE THREAD

**Issue by akrauze** [Adamm00/IPSet_ASUS#111] opened 2023-02-17 11:37 UTC
###### Brief Description Of Issue
Skynet does honor banning 1.1.1.1, 1.0.0.1, 8.8.8.8 or 8.8.4.4 ass those are "private" IPs for Skynet.

See: https://github.com/Adamm00/IPSet_ASUS/blob/master/firewall.sh#L756

###### Steps To Reproduce Issue
1. Execute ``firewall ban ip 8.8.8.8``
2. Check DNS server at 8.8.8.8 is still accessible

###### Expected Behaviour
All banned IPs are banned

**Comment by akrauze** [comment] 2023-02-17 12:33
Something in these lines would do the trick:
```sh
Filter_PrivateIP() {
    if [ "$unbanprivateip" = "enabled" ]; then
        grep -vE '^(0\.|10\.|100\.(6[4-9]|[7-9][0-9]|1[0-1][0-9]|12[0-7])\.|127\.|169\.254\.|172\.1[6-9]\.|172\.2[0-9]\.|172\.3[0-1]\.|192\.0\.0\.|192\.0\.2\.|192\.168\.|198\.(1[8-9])\.|198\.51\.100\.|203\.0\.113\.|2(2[4-9]|[3-4][0-9]|5[0-5])\.|8\.8\.8\.8|8\.8\.4\.4|1\.1\.1\.1|1\.0\.0\.1)'
    else
        grep -vE '^(0\.|10\.|100\.(6[4-9]|[7-9][0-9]|1[0-1][0-9]|12[0-7])\.|127\.|169\.254\.|172\.1[6-9]\.|172\.2[0-9]\.|172\.3[0-1]\.|192\.0\.0\.|192\.0\.2\.|192\.168\.|198\.(1[8-9])\.|198\.51\.100\.|203\.0\.113\.|2(2[4-9]|[3-4][0-9]|5[0-5])\.)'
    fi
}
```

Currently I'm using the following "custom" update script:
```sh
/usr/sbin/curl -s "https://raw.githubusercontent.com/Adamm00/IPSet_ASUS/master/firewall.sh" -o "/jffs/scripts/firewall" && /bin/sed -i 's~|8\\\.8\\\.8\\\.8|8\\\.8\\\.4\\\.4|1\\\.1\\\.1\\\.1|1\\\.0\\\.0\\\.1~~g' "/jffs/scripts/firewall" && chmod 755 /jffs/scripts/firewall; ipset del Skynet-Whitelist 1.1.1.1;ipset del Skynet-Whitelist 1.0.0.1;ipset del Skynet-Whitelist 8.8.8.8;ipset del Skynet-Whitelist 8.8.4.4;/jffs/scripts/firewall restart
```

**Comment by crkinard** [comment] 2023-05-24 20:24
Is this fixed? I tell Skynet to ban 8.8.8.8 and I can no longer ping it.

**Comment by jumpsmm7** [comment] 2023-05-26 05:35
Weird, Is the goal here to Ban these IP addresses? or not to ban? do you want them hard-coded as un-bannable?  or are you expecting to be able to ban these IP addresses?

**Comment by crkinard** [comment] 2023-06-19 20:56
I take back my previous comment. Skynet refuses to ban google DNS. 

It should NOT do this. No IP's should be hard coded into the whitelist.

**Comment by jumpsmm7** [comment] 2023-06-20 19:19
> I take back my previous comment. Skynet refuses to ban google DNS.
> 
> It should NOT do this. No IP's should be hard coded into the whitelist.

If your intention is to ban these then you could easily do:

`firewall settings iot ban 8.8.8.8`
`firewall settings iot ban 8.8.4.4`

But you must manually do this. Otherwise, these addresses are hardcoded into skynet to prevent unforeseen breakage.

**Comment by dave14305** [comment] 2023-06-20 19:47
https://www.snbforums.com/threads/skynet-router-firewall-security-enhancements.16798/page-122#post-395244

https://www.snbforums.com/threads/skynet-router-firewall-security-enhancements.16798/page-170#post-441281

**Comment by jumpsmm7** [comment] 2023-06-20 19:55
@dave14305 
From what I can tell, the addresses are still manually ban-able. Is this a desired behavior?

**Comment by Adamm00** [comment] 2023-06-21 07:52
Filter_PrivateIP() was designed as a failsafe, users who added badly curated lists or weird resolving domains were losing all connectivity.

These addresses still can be manually banned;

```
skynet@GT-AXE16000-9D20:/tmp/home/root# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=118 time=16.344 ms
64 bytes from 8.8.8.8: seq=1 ttl=118 time=16.183 ms
64 bytes from 8.8.8.8: seq=2 ttl=118 time=16.101 ms
64 bytes from 8.8.8.8: seq=3 ttl=118 time=15.913 ms
64 bytes from 8.8.8.8: seq=4 ttl=118 time=16.279 ms
64 bytes from 8.8.8.8: seq=5 ttl=118 time=16.202 ms
^C
--- 8.8.8.8 ping statistics ---
6 packets transmitted, 6 packets received, 0% packet loss
round-trip min/avg/max = 15.913/16.170/16.344 ms

skynet@GT-AXE16000-9D20:/tmp/home/root# firewall ban ip 8.8.8.8 test
#############################################################################################################
#                                                                                                           #
#                  ███████╗██╗  ██╗██╗   ██╗███╗   ██╗███████╗████████╗    ██╗   ██╗███████╗                #
#                  ██╔════╝██║ ██╔╝╚██╗ ██╔╝████╗  ██║██╔════╝╚══██╔══╝    ██║   ██║╚════██║                #
#                  ███████╗█████╔╝  ╚████╔╝ ██╔██╗ ██║█████╗     ██║       ██║   ██║    ██╔╝                #
#                  ╚════██║██╔═██╗   ╚██╔╝  ██║╚██╗██║██╔══╝     ██║       ╚██╗ ██╔╝   ██╔╝                 #
#                  ███████║██║  ██╗   ██║   ██║ ╚████║███████╗   ██║        ╚████╔╝    ██║                  #
#                  ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝╚══════╝   ╚═╝         ╚═══╝     ╚═╝                  #
#                                                                                                           #
#                                 Router Firewall And Security Enhancements                                 #
#                             By Adamm -  https://github.com/Adamm00/IPSet_ASUS                             #
#                                            05/06/2023 - v7.4.4                                            #
#############################################################################################################


=============================================================================================================


[i] Banning 8.8.8.8
[i] Saving Changes


=============================================================================================================


[#] 38374 IPs (+1) -- 2307 Ranges Banned (+0) || 13388 Inbound -- 0 Outbound Connections Blocked! [ban] [1s]

skynet@GT-AXE16000-9D20:/tmp/home/root# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: sendto: Operation not permitted
skynet@GT-AXE16000-9D20:/tmp/home/root#
```

**Closed by Adamm00** 2023-06-21 07:52 UTC

**Comment by jumpsmm7** [comment] 2023-06-21 19:47
Thanks for clarification @Adamm00 , this means that this is intended by design to prevent user error or the unknowing user from breaking their own dns services by blocking a domain or using a list that has 1.1.1.1, 1.0.0.1, 8.8.8.8, or 8.8.4.4 as either its ip or ip address present in a block list. Yet users can still manually ban these ip addresses if they so choose to do so, but it has to be by manually banning the ip address itself.
